dataset: places365
base_dir: '/data/aryan/Seekg/Datasets/places365/Object_annotations'
subset_path: ''
KG_path: '/data/aryan/Seekg/Datasets/places365/places365places_KG.pkl'

gsnn_path: ''
epochs: 100
batch_size: 1
alpha: 0.1
lr: 0.01

gcn:
  n_feat: 100
  n_hid: 100
  n_out: 100
  n_layers: 1
  dropout: 0.5
  