dataset: ade20k
base_dir: '/data/aryan/Seekg/MGNN/datasets/ade20k/image_info_dict.pkl'
data_dir: '/data/aryan/Seekg/Datasets/ade20k/ADE20K_2021_17_01/images'
subset_path: ''
KG_path: '/data/aryan/Seekg/Datasets/ade20k/ade_KG_test.pkl'

gsnn_path: ''
# vit_path: '/data/aryan/Seekg/MGNN/results/vit.pth'
vit_path: ''
epochs: 5
batch_size: 1
alpha: 0.1
lr: 0.0001

gcn:
  n_feat: 100
  n_hid: 100
  n_out: 100
  n_layers: 1
  dropout: 0.5
  image_conditioning: True

gsnn:
  n_steps: 1
  step_threshold: 0.98

vit:
  img_dim: 768
  